# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djaken', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.TextField(editable=False)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djaken.Note')),
            ],
        ),
    ]
